### ISSUE TITLE
РК №2

### ISSUE THREAD

**Issue by edward-grolsh** [frontend-park-mail-ru/2019_1_WAO#4]
- [x] сделать стартовый экранов меню, а не экран регистрации. Либо добавить кнопку "продолжить без регистрации"
- [x] разные шрифты на кнопках в форме регистрации
- [x] либо заиспользовать поле с почтой, либо убрать его
- [x] в поле с инфой об пользователе в правом верхнем углу нет ховеров на кнопках "выйти" и "меню".  
- [ ] при выходе в меню, остается кнопка "меню" в правом верхнем углу
- [x] сделать разные меню для зарегистрированного и незарегистрированного пользователя
- [x] меню лучше расположить чуть ближе к центру экрана
- [x] если зажать кнопку вправо, то бесконечно набираются очки в игре
- [x] не очень понятны граничные условия игры. когда я проиграю?  
- [ ] в меню об игре аватарки все сжало. либо узкие, либо широкие. попробуйте вместо img использовать div в аттрибутами: 
```css
.developer__image {
    background-image: url(https://pp.userapi.com/c846122/v846122120/137202/wK6kCZLP2Pc.jpg);
    background-size: cover;
    background-position: center center;
    width: 100px;
    height: 100px;
    border: solid;
    border-color: #979797;
    border-radius: 50%;
}
```
